2025-08-12 14:53:57,750 - ERROR - Необработанное исключение: ValueError: invalid literal for int() with base 10: ''
2025-08-12 14:53:57,751 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 3710, in tool_page
    page()
    ~~~~^^
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 3881, in page
    number_games = int(txt[:t])
ValueError: invalid literal for int() with base 10: ''
