2025-08-11 09:53:08,585 - ERROR - Необработанное исключение: ValueError: sex is not null but has no default
2025-08-11 09:53:08,609 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 18280, in proba
    migrate(migrator.add_column('players', 'sex', sex)) # Добавление столбца (таблица, столбец, повтор название столбца)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\Competitions_TT_v1.2\venv\Lib\site-packages\playhouse\migrate.py", line 947, in migrate
    operation.run()
    ~~~~~~~~~~~~~^^
  File "C:\Users\Alex\Competitions_TT_v1.2\venv\Lib\site-packages\playhouse\migrate.py", line 162, in run
    self._handle_result(method(*self.args, **kwargs))
                        ~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\Competitions_TT_v1.2\venv\Lib\site-packages\playhouse\migrate.py", line 170, in inner
    return fn(self, *args, **kwargs)
  File "C:\Users\Alex\Competitions_TT_v1.2\venv\Lib\site-packages\playhouse\migrate.py", line 320, in add_column
    raise ValueError('%s is not null but has no default' % column_name)
ValueError: sex is not null but has no default
