2025-08-15 14:47:04,826 - ERROR - Необработанное исключение: UnboundLocalError: cannot access local variable 'stage' where it is not associated with a value
2025-08-15 14:47:04,827 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 1050, in system_made
    system_competition()
    ~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 4853, in system_competition
    flag_choice = ready_choice(stage)
                               ^^^^^
UnboundLocalError: cannot access local variable 'stage' where it is not associated with a value
