2025-08-15 12:39:22,980 - ERROR - Необработанное исключение: NameError: name 'my_wn' is not defined
2025-08-15 12:39:22,981 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 1050, in system_made
    system_competition()
    ~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\Alex\Competitions_TT_v1.2\main.py", line 4877, in system_competition
    my_wn.tabWidget.setTabEnabled(2, True)
    ^^^^^
NameError: name 'my_wn' is not defined
